[workspace]
members = [
    "programs/*",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.test]
opt-level = 0
debug = true

[profile.bench]
opt-level = 3
lto = true
codegen-units = 1
