[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "base58>=2.1.1",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "solana>=0.36.6",
    "streamlit>=1.44.1",
]
