[server]
# Set to false to disable browser launch on start
headless = true

# Enable CORS protection for the server. Set to false if needed for certain APIs
enableCORS = false

# Enable CSRF protection for the server. Set to false if you need to disable it
enableXsrfProtection = false

# The address where the server will listen for client and/or websocket connections
address = "0.0.0.0"

# The port where the server will listen for browser connections
port = 8501

# Enable development mode for hot reloading
runOnSave = false

# Controls file watcher type for development
# Options: "auto", "watchdog", "poll", or "none"
fileWatcherType = "none"

# Set to true to enable websocket compression
enableWebsocketCompression = true

[browser]
# Set to false to disable the "Get started" menu
gatherUsageStats = false

[theme]
# Theme settings
base = "dark"
primaryColor = "#14F195"
backgroundColor = "#131313"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
font = "sans serif"