[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200  # Max file upload size in MB
enableStaticServing = false  # Disable static file serving

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
base = "dark"
primaryColor = "#14F195"
backgroundColor = "#131313"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
font = "sans serif"

# Remove deprecated scheduler settings
[scheduler]
# Retry timeout is no longer configurable in this version

[client]
showErrorDetails = true

[scheduler]
retryTimeout = 300

[ui]
hideTopBar = false

[mapbox]
token = ""  # Add your Mapbox token here if needed

[logger]
level = "info"
