[server]
headless = true
port = 8501
baseUrlPath = "/"
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200  # Max file upload size in MB
enableStaticServing = true
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
base = "dark"
primaryColor = "#14F195"
backgroundColor = "#131313"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
font = "sans serif"

[client]
showErrorDetails = true

[ui]
hideTopBar = false

[runner]
fixMatplotlib = true

[mapbox]
token = ""  # Add your Mapbox token here if needed

[logger]
level = "info"

[scheduler]
heartbeatCallbackMs = 0  # Disable heartbeat for cloud deployment
