# Copy this file to secrets.toml and fill in your actual values
# This file is just an example and should not contain real secrets

# Database configuration
[database]
# url = "postgresql://user:password@localhost:5432/dbname"

# API Keys
[api_keys]
# solana_mainnet = "your_mainnet_rpc_url_here"
# solana_devnet = "your_devnet_rpc_url_here"

# Other secrets
[secrets]
# secret_key = "your_secret_key_here"
